#!/usr/bin/env bash
# script that changes the IP of your home computer
sed 's/127.0.0.1/127.0.0.2/' /etc/hosts | sudo tee /etc/hosts > /dev/null
if grep -q "facebook.com" /etc/hosts; then
    sed 's/.*facebook.com/8.8.8.8 facebook.com/' /etc/hosts | sudo tee /etc/hosts > /dev/null
else
    echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts > /dev/null
fi
